name: 黄雪良的博客
description: Blogging about stuffs
meta_description: "黄雪良的博客，前端技术博客s"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         '黄雪良'
